AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: chatapp-serverless

Resources:
  ChatApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: '''*'''
        AllowMethods: '''GET,POST,OPTIONS'''

  ChatApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          MONGODB_URL: !Sub '{{resolve:ssm:Parameter_MONGODB_URL}}'
          SECRET_KEY: !Sub '{{resolve:ssm:Parameter_SECRET_KEY}}'
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ChatApiGateway
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway URL for the Chat App
    Value: !Sub https://${ChatApiGateway}.execute-api.eu-west-1.amazonaws.com/Prod/login